version: '3.9'

services:
  db:
    image: postgres:16

    environment:
      POSTGRES_DB: quote_handler_db
      PG_USER: ${PG_USER:-user}
      PG_PASSWORD: ${PG_PASSWORD:-password}
      PGDATA: /var/lib/postgresql/data/

    restart: on-failure

    ports:
      - "5432:5432"

    volumes:
      - database-data:/var/lib/postgresql/data

    networks:
      - handle-network

  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/quote_handler_db
      PG_USER: ${PG_USER:-user}
      PG_PASSWORD: ${PG_PASSWORD:-password}

    ports:
      - "8080:8080"

    restart: always

    depends_on:
      - db

    networks:
      - handle-network


networks:
  handle-network:

volumes:
  database-data:
