version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=quote_handler_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bagascript2024
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - handle-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - handle-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/quote_handler_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: bagascript2024

networks:
  handle-network:

volumes:
  database-data:
